trigger: none
pr: none
schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - main
  always: true
parameters:
  - name: platforms
    type: object
    default:
      - vs
      - centec-arm64
      - marvell-armhf

jobs:
  - job: Build
    pool: sonic-mirror-westus2-2
    timeoutInMinutes: 20
    variables:
      - group: Debian-Mirror-Common
    steps:
      - checkout: self
        clean: true
      - ${{ each platform in parameters.platforms }}:
        - task: DownloadPipelineArtifact@2
          displayName: Download ${{ platform }} versions-docker file
          inputs:
            source: specific
            project: build
            pipeline: Azure.sonic-buildimage.official.${{ platform }}
            runVersion: 'latestFromBranch'
            runBranch: 'refs/heads/master'
            path: download
            patterns: |
              **/target/versions/default/versions-docker
      - script: |
          set -ex
          az login -u $(ApplicationId) --service-principal --tenant $(AzureTenant) -p "$ApplicationKey"
          images=$(find download -name versions-docker | xargs -i grep -v "==$" {} | awk -F== '{print$1}' | sed -e "s/amd64://" -e "s/arm64://" -e "s/armhf://" | sort -u )
          for i in $images
          do
            az acr import -n PublicMirror --source docker.io/$i --image $i --force || az acr import -n PublicMirror --source docker.io/library/$i --image $i --force
          done
        env:
          ApplicationKey: '$(ApplicationKey)'
